apps/login_and_registration/urls.py
from django.conf.urls import url
from . import views

app_name = "login_and_registration"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^profile$', views.profile),
    url(r'^profile/(?P<id>\d+)/delete$', views.delete, name = 'my_delete'),
    url(r'^logout$', views.logout, name= 'logout'),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_and_registration.urls', namespace="login_and_registration")),
    url(r'^dashboard/', include('apps.wish_list.urls', namespace="wish_list")),
]

apps/login_and_registration/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
import re, bcrypt

regex_pattern_email = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
regex_pattern_password = re.compile(r'[A-Za-z0-9@#$%^&+=]{8,}')

class UserManager(models.Manager):

    def login_validation(self, data):

        errors = []
        username = data['username']
        password = data['password'].encode()

        try:
            user = User.objects.get(username=username)
            hashed_pw = user.password.encode()

            if hashed_pw == bcrypt.hashpw(password, hashed_pw):
                return (True, user)
        except:
                errors.append("Incorrect username or password")
        return (False, errors)

    def registration_validation(self, data):

        errors = []
        first_name = data['first_name']
        last_name = data['last_name']
        username = data['username']
        email = data['email']
        password = data['password']
        confirm_password = data['confirm_password']
        birthdate = data['birthdate']

        if len(first_name) < 2:
            errors.append('first name must be at least two characters')

        if len(last_name) <2:
            errors.append('last name must be at least two characters')

        if len(username) <2:
            errors.append('username must be at least two characters')

        if len(email) < 1:
            errors.append('email must be filled out')
        elif not regex_pattern_email.match(email):
            errors.append('email must be valid')

        if len(password) < 8:
            errors.append('password must be at least 8 characters')
        elif not regex_pattern_password.match(password):
            errors.append('password must contain valid characters')

        if len(confirm_password) <= 1:
            errors.append('confirm password must not be blank')
        if confirm_password != password:
            errors.append('confirm password does not match')

        if len(birthdate) > 0:
            try:
                birth_date_format = datetime.strptime(data['birthdate'], '%Y-%m-%d')
            except:
                errors.append("birthdate is invalid")
        if len(birthdate) < 1:
            errors.append('birthdate must not be empty')

        if not errors:
            try:
                match_email = self.get(email=email)
                errors.append('email already exists')
                match_username = self.get(username=username)
                erros.append('username already exists')
                return (False, errors)
            except:
                password = password.encode()
                pw_hash = bcrypt.hashpw(password, bcrypt.gensalt())
                user = self.create(first_name=first_name, last_name=last_name, username=username, email=email, password=pw_hash, birthdate=birth_date_format)
                return (True, user)
        else:
            return (False, errors)

    def delete_user(self, id):
        user = User.objects.filter(id=id)
        user.delete()
        print '*************'
        print user
        return (True)

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    birthdate = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    def __unicode__(self):
        return self.username

apps/login_and_registration/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User

def index(request):
    return render(request, 'login_and_registration/index.html')

def profile(request):
    return render(request, 'login_and_registration/profile.html')

def login(request):
    valid, response = User.objects.login_validation(request.POST)

    if not valid:
        for error in response:
            messages.error(request, error)
        return redirect(reverse('login_and_registration:index'))
    else:
        messages.success(request, "Welcome Back!")
        request.session['user_id'] = response.id
        request.session['first_name'] = response.first_name
    return redirect(reverse('wish_list:index'))

def register(request):
    valid, response = User.objects.registration_validation(request.POST)

    if not valid:
        for error in response:
            messages.error(request, error)
        return redirect(reverse('login_and_registration:index'))
    else:
        messages.success(request, "Thanks for registering!")
        request.session['user_id'] = response.id
        request.session['first_name'] = response.first_name
    return redirect(reverse('wish_list:index'))

def delete(request, id):
    valid = User.objects.delete_user(id)
    return redirect('/')

def logout(request):
    request.session.clear()
    return redirect('/')

apps/login_and_registration/templates/login_and_registration/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'login_and_registration/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login_and_registration/skeleton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login_and_registration/styles.css' %}">
    <title></title>
  </head>
  <body>
    <label for="">Welcome!</label>
    {% if messages %}
      {% for message in messages%}
        <p> {{ message }} </p>
      {% endfor %}
    {% endif %}
    <label for="login">Login</label>
    <form class="login" action="{% url 'login_and_registration:login' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username">
      <input type="password" name="password" placeholder="Password">
      <input type="submit" name="login" value="Login!">
    </form>
    <label for="register">Register</label>
    <form class="register" action="{% url 'login_and_registration:register' %}" method="post">
      {% csrf_token %}
      <input type="text" name="first_name" placeholder="First Name">
      <input type="text" name="last_name" placeholder="Last Name">
      <input type="text" name="username" placeholder="Username">
      <input type="text" name="email" placeholder="Email">
      <input type="password" name="password" placeholder="Password">
      <p>*Password should be at least 8 characters</p>
      <input type="password" name="confirm_password" placeholder="Confirm Password">
      <label for="date">Date Hired:</label>
      <input type="date" name="birthdate" value="">
      <input type="submit" name="submit" value="Register!">
    </form>
  </body>
</html>

apps/login_and_registration/templates/login_and_registration/profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
	  <link rel="stylesheet" type="text/css" href="{% static 'login_and_registration/normalize.css' %}">
	  <link rel="stylesheet" type="text/css" href="{% static 'login_and_registration/skeleton.css' %}">
	  <link rel="stylesheet" type="text/css" href="{% static 'login_and_registration/styles.css' %}">
    <title> {{ user.first_name }} {{ user.last_name }}</title>
  </head>
  {% for message in messages %}
  <h1>{{ message }}</h1>
  {% endfor %}
  <body>
    <h2>This is your BigFoot Portal!!</h2>
    <h3>{{ request.session.first_name }}, Would you like to report a BigFoot sighting?</h3>
    <form class="" action="{% url 'my_delete' request.session.user_id %}" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Delete User">
    </form>
      <a href="{% url 'logout' %}">Logout?</a>
  </body>
</html>