apps/wish_list/urls.py
from django.conf.urls import url
from . import views

app_name = "wish_list"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^wish_items/create$', views.create, name='create'),
    url(r'^wish_items/process$', views.process, name='process'),
    url(r'^wish_items/add/(?P<wish_id>\d+)$', views.add_item, name='add_item'),
    url(r'^wish_items/delete/(?P<wish_id>\d+)$', views.delete_item, name='delete_item'),
    url(r'^wish_items/remove/(?P<wish_id>\d+)$', views.remove_item, name='remove_item'),
    url(r'^wish_items/(?P<wish_id>\d+)$', views.wish_detail, name='wish_detail'),
    url(r'^logout$', views.logout),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_and_registration.urls', namespace="login_and_registration")),
    url(r'^dashboard/', include('apps.wish_list.urls', namespace="wish_list")),
]

apps/wish_list/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from ..login_and_registration.models import User

class WishManager(models.Manager):

    def delete_item(self, user_id, wish_id):
        try:
            item = self.get(id=wish_id)
            if item.created_by.id == user_id:
                item.delete()
                return True
            else:
                return False
        except:
            pass
            return False

    def remove_item(self, user_id, wish_id):
        try:
            user = User.objects.get(id=user_id)
            item = self.get(id=wish_id)
            item.added_by.remove(user)
            return True
        except:
            pass
            return False

    def wish_detail(self, wish_id):
        try:
            wish = self.get(id=wish_id)
            return (True, wish)
        except:
            return (False, 'wish does not exist')

    def my_items(self, user_id):
        items = self.filter(added_by__id=user_id)
        return items

    def others_items(self, user_id):
        items = Wish.objects.exclude(added_by__id=user_id)
        return items

    def adding_item(self, user_id, wish_id):
        errors = []
        try:
            user = User.objects.get(id=user_id)
            item = self.get(id=wish_id)
            item.added_by.add(user)
            return (True, item)
        except:
            errors.append('user or item does not exit')
            return (False, errors)

    def create_item(self, data, user_id):
        errors = []
        item = data['item']
        user = User.objects.filter(id=user_id)

        if len(item) < 3:
            errors.append('item must be more than 3 characters long')

        if not errors:
            try:
                match_item = self.get(item=item)
                errors.append('item already exists')
                return (False, errors)
            except:
                item = self.create(item=item, created_by=user[0])
                item.added_by.add(user[0])
                return (True, item)
        else:
            return (False, errors)

class Wish(models.Model):
    item = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    added_by = models.ManyToManyField(User, related_name='added_items')
    created_by = models.ForeignKey(User, related_name='created_items')
    objects = WishManager()

    def __unicode__(self):
        return self.item

apps/wish_list/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Wish
from ..login_and_registration.models import User

def index(request):
    user_id = request.session['user_id']
    my_items = Wish.objects.my_items(user_id)
    others_items = Wish.objects.others_items(user_id)
    context = {
        'my_items':my_items,
        'others_items':others_items,
    }
    return render(request, 'wish_list/dashboard.html', context)

def create(request):
    return render(request, 'wish_list/create.html')

def process(request):
    user_id = request.session['user_id']
    valid, response = Wish.objects.create_item(request.POST, user_id)
    if not valid:
        for error in response:
            print error
            messages.error(request, error)
        return redirect(reverse('wish_list:create'))
    else:
        messages.success(request, "Item has been added!")
    return redirect(reverse('wish_list:index'))

def add_item(request, wish_id):
    user_id = request.session['user_id']
    user_items = Wish.objects.adding_item(user_id, wish_id)
    return redirect(reverse('wish_list:index'))

def delete_item(request, wish_id):
    user_id = request.session['user_id']
    item = Wish.objects.delete_item(user_id, wish_id)
    return redirect(reverse('wish_list:index'))

def remove_item(request, wish_id):
    user_id = request.session['user_id']
    item = Wish.objects.remove_item(user_id, wish_id)
    return redirect(reverse('wish_list:index'))

def wish_detail(request, wish_id):
    users = User.objects.filter(added_items__id=wish_id)
    valid, wish = Wish.objects.wish_detail(wish_id)
    if valid:
        context = {
            'users':users,
            'wish':wish,
            }
    else:
        messages.error(request, wish)
    return render(request, 'wish_list/wish_details.html', context)

def logout(request):
    return redirect(reverse('login_and_registration:index'))

apps/wish_list/templates/wish_list/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/skeleton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/styles.css' %}">
    <title></title>
  </head>
  <body>
    <a href="{% url 'wish_list:index' %}">Home</a>
    <a href="{% url 'login_and_registration:index' %}">Logout</a>
    <h1>Create a New Wish List Item</h1>
    {% if messages %}
      {% for message in messages%}
    <p> {{ message }} </p>
      {% endfor %}
    {% endif %}
    <form class="" action="{% url 'wish_list:process' %}" method="post">
      {% csrf_token %}
      <label for="item">Item/Product:</label>
      <input type="text" name="item" placeholder="Item/Product">
      <input type="submit" name="submit" value="Add">
    </form>
  </body>
</html>

apps/wish_list/templates/wish_list/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/skeleton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/styles.css' %}">
    <title></title>
  </head>
  <body>
    <a href="{% url 'login_and_registration:index' %}">Logout</a>
    <h1>Hello, {{ request.session.first_name }}</h1>
    <h2>Your Wish List:</h2>
    {% for item in my_items %}
      {% if item.created_by.id == request.session.user_id %}
    <table>
      <tr>
        <th>Item</th>
        <th>Added By</th>
        <th>Date Added</th>
        <th>Action</th>
      </tr>
      <td><a href="{% url 'wish_list:wish_detail' item.id %}">{{ item.item }}</a></td><td>{{ item.created_by }}</td><td>{{ item.created_at }}</td><td><form action="{% url 'wish_list:delete_item' item.id %}" method="post">{% csrf_token %}<input type="submit" name="" value="Delete"></td>
      {% else %}
      <td><a href="{% url 'wish_list:wish_detail' item.id %}">{{ item.item }}</a>{{ item.created_by }} {{ item.created_at }}<a href="{% url 'wish_list:remove_item' item.id %}">Remove from My Wish List</a></td>
      {% endif %}
    {% endfor %}
    </table>
    <h3>Others Wish List:</h3>
    <table>
      <tr>
    {% for item in others_items %}
        <th>Item</th>
        <th>Added By</th>
        <th>Date Added</th>
        <th>Action</th>
      </tr>
      <td><a href="{% url 'wish_list:wish_detail' item.id %}">{{ item.item }}</a><td>{{ item.created_by }}</td> <td>{{ item.created_at }}</td><td><a href="{% url 'wish_list:add_item' item.id %}">Add to my Wishlist</a></td>
    {% endfor %}
      </tr>
    </table>
    <a href="{% url 'wish_list:create' %}">Add Item</a>
  </body>
</html>

apps/wish_list/templates/wish_list/wish_details.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/skeleton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wish_list/styles.css' %}">
    <title></title>
  </head>
  <body>
    <a href="{% url 'wish_list:index' %}">Home</a>
    <a href="{% url 'login_and_registration:index' %}">Logout</a>
    <h1>{{ wish.item }}</h1>
    <p>Users who added this product/item under their wish list:</p>
    {% for user in users %}
     <ul><li>{{user.username}}</li></ul>
    {% endfor %}
  </body>
</html>